language: node_js
sudo: false
node_js:
- "4.7.3"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
- gulp test
- gulp karma
- gulp smoke

language: node_js


